### ISSUE TITLE
Usage in windows

### ISSUE THREAD

**Issue by InverseInductor** [MS3FGX/SomaFM#2]
Hi,

I'm unsure how to get this to work once installed using pip in windows.
Is this supported?

**Comment by MS3FGX** [comment]
I'm not aware of anyone ever using it in Windows before, but in theory it should be workable. Does it show an error message when you try to start it?

**Comment by MS3FGX** [comment]
So just as an update to this I finally had a chance to run the script on a Windows machine, and no it definitely doesn't work out of the box. In hindsight I should have known better, of course the paths are all Unix style.

I should be able to have some kind of switch that detects the OS its running on and change path/files to something more appropriate. That will at least be a step in the right direction.

**Comment by MS3FGX** [comment]
@InverseInductor A long time coming, but I did recently get my hands on a Windows computer and addressed the handful of issues that was keeping the script from running. Right now it only seems to work with MPlayer, but it's a start.

You'll need to have MPlayer installed somewhere the script can access it. I found the easiest way was to just drop the binary in the directory with the somafm script, but I imagine there's some way to add it to the Windows PATH environment variable as well.

I haven't pushed the new update to PyPi yet (will do so soon), but you should be able to download the zip file from the new release and try it that way.
