### ISSUE TITLE
Doesn't quit properly when window is killed (i3)

### ISSUE THREAD

**Issue by jamisonrobey** [MS3FGX/SomaFM#8]
Hi,

Really like this project its awesome. The only bug I run into is when I kill a terminal running `somafm` in i3 (not sure what i3 calls). The next time I call `somafm` I get the message: 

```
SomaFM is already running!
If you think this message is a mistake, delete the file: /tmp/soma.pid
```

Which I resolve by deleting said file.

Anyways, I tried to have a look at the code but I'm not versed in building CLI apps so I couldn't figure it out.

Thanks again for the sweet package

Edit: 
The specific thing i3 is calling is:
```
# kill focused window
bindsym $mod+Shift+q kill
```

**Comment by jamisonrobey** [comment]
https://github.com/MS3FGX/SomaFM/pull/9

**Comment by MS3FGX** [comment]
I'm actually trying to remember why I included the whole PID thing anyway. There must have been some reason that running two instances of the player at the same time messed with things...maybe when streaming to Chromecast and trying to start another local copy?

Anyway, this was a clear improvement so I appreciate the PR.
